# Generated by Django 3.0.5 on 2021-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0002_courier_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='owner',
            new_name='user',
        ),
    ]
