# Generated by Django 3.0.5 on 2021-09-10 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0003_auto_20210907_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
