# Generated by Django 3.0.5 on 2021-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0004_courier_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='date_recieved',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='student_rollno',
        ),
        migrations.AddField(
            model_name='courier',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='tracking_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
