# Generated by Django 3.0.5 on 2022-04-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0008_contact_message_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='phone',
            new_name='sender_name',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='name',
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='service',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
